name: AC Bandit

on:
  pull_request:
    branches:
      - dev
      - staging*
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Set up venv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        mkdir venv
        virtualenv venv/venv-2.16

    - name: Install dependencies
      run: |
        source venv/venv-2.16/bin/activate
        python -m pip install --upgrade pip
        pip install bandit
        pip install bandit_sarif_formatter

    - name: Run ac_bandit
      run: |
        source venv/venv-2.16/bin/activate
        ./ac --ac-bandit --level l

    - name: SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif